server:
  port: 8080
kafka:
  url: kafka:9092
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
