server:
  port: 8080
kafka:
  topic:
    name: topic1
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: "kafka:9092"
    consumer:
      group-id: "group1"
